### PR TITLE
veax-void-hw2-attempt1

### PR DESCRIPTION
**Pull request by ivanvoid**
---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Comment by ivanvoid** [comment]
Hmm `No module named pybind11`
```
g++ -O3 -Wall -shared -std=c++11 -fPIC `python3 -m pybind11 --includes`  package.cpp -o package`python3-config --extension-suffix`
/usr/bin/python3: No module named pybind11
In file included from /usr/include/pybind11/pytypes.h:12,
                 from /usr/include/pybind11/cast.h:13,
                 from /usr/include/pybind11/attr.h:13,
                 from /usr/include/pybind11/pybind11.h:44,
                 from package.cpp:1:
/usr/include/pybind11/detail/common.h:112:10: fatal error: Python.h: No such file or directory
  112 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:8: package] Error 1
failure
Error: Process completed with exit code 1.
```

**Comment by q40603** [comment]
Maybe change your pybuild to $(python3-config --includes) -Iextern/pybind11/include can work.

**Comment by q40603** [comment]
https://github.com/dboyliao/pybind11_learn/blob/master/pybind11_exp/cpp/Makefile

**Comment by tigercosmos** [comment]
who are u?

**Comment by veax-void** [comment]
Hi, Ivan Kakhaev (柯亦凡) I attend Numerical Software Development course 5301 109 spring.

**Comment by veax-void** [comment]
> who are u?
Hi, Ivan Kakhaev (柯亦凡) I attend Numerical Software Development course 5301 109 spring.

**Comment by ivanvoid** [comment]
> who are u?

Hi, Ivan Kakhaev (柯亦凡) I attend Numerical Software Development course 5301 109 spring.
Can I ask why I graded 0 for hw2? I uploaded it in time.

**Comment by veax-void** [comment]
Hi, Ivan Kakhaev (柯亦凡) I attend Numerical Software Development course 5301
109 spring.
Can I ask why I graded 0 for hw2? I uploaded it in time.

**Comment by tigercosmos** [comment]
Okay. Remember to upload to E3 next time.

**Pull request merged**
