### PR TITLE
Bhbruce proposal attempt1

### PR DESCRIPTION
**Pull request by bhbruce**
---
A good PR should include the following parts:

- [X] A clear title
- [X] A meaningful message for PR, as well as its commits
- [X] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

### CODE REVIEW

**Comment by yungyuc** [comment]
@bhbruce The PR should only contain commits related to the proposal.  Please get rid of other commits e.g. those for HW3.

**Comment by yungyuc** [comment]
Leave a comment after you get it clean.

**Comment by yungyuc** [comment]
@bhbruce I just realized that you are auditing.  If you do not plan to do the term project, feel free to withdraw the proposal.  You are more than welcome to do the project, though.

**Comment by bhbruce** [comment]
> @bhbruce I just realized that you are auditing. If you do not plan to do the term project, feel free to withdraw the proposal. You are more than welcome to do the project, though.

Thank you @yungyuc. I prefer to do the final project. However, I am not sure whether this topic is related?

**Comment by yungyuc** [comment]
> > @bhbruce I just realized that you are auditing. If you do not plan to do the term project, feel free to withdraw the proposal. You are more than welcome to do the project, though.
> 
> Thank you @yungyuc. I prefer to do the final project. However, I am not sure whether this topic is related?

I have not started reviewing your proposal for the PR is not organized correctly.  After you correct the PR I'll take a look and comment.  We can also discuss in person in the classroom.

**Pull request closed without merging**
